### ISSUE TITLE
[1.12.2] team issues

### ISSUE THREAD

**Issue by kreezxil** [Thutmose/ThutEssentials#30]
# Versions
Mod: 1.12.2-2.1.6
Forge: 1.12.2-14.23.3.2678

## Problem
In game it says I created a team but the console says I failed to create the team.
In game when i list the teams it only shows plebs thus confirming the team I created failed.
It also won't let me join the the admin team although I am op
not even from the console

## Data
excerpt from the console log
```
> op Kreezxil
[10:40:24] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Opped Kreezxil
[10:40:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Kreezxil: Set own game mode to Creative Mode]
[10:40:57] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: createTeam
java.lang.ArrayIndexOutOfBoundsException: 0
        at thut.essentials.commands.land.Create.func_184881_a(Create.java:21) ~[Create.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
> set
setTeamAdmin   setteamadmin
> set
setTeamAdmin   setteamadmin
> setteamadmin kreezxil
[10:45:03] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: You must specify which player you wish to perform this action on.
> setteamadmin Kreezxil
[10:45:13] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: You must specify which player you wish to perform this action on.
>
```
## Screens

![screenshot_7](https://user-images.githubusercontent.com/3880072/39711159-83111b44-51e4-11e8-84a1-269369bb3766.png)

## Latest.log
http://dpaste.com//1XHGMDQ

**Comment by kreezxil** [comment]
it is  highly possible this is not a bug. And more a problem with an incomplete manual or actually the lack of a manual. This mod needs a wiki badly to explain how to setup things. I found a section called Staff in the config and added my name to it.

I assume that allow me to have access to the Admin commands.

However, it should have still allowed me to create a non admin team.

**Comment by Thutmose** [comment]
If it made an error in console, then it is probably something I should look into, the mod does need a wiki, but I have not the time to make one for it.

It could be user error, or it could be something that broke in a recent forge, I will try to look into it in a few hours

**Comment by Thutmose** [comment]
I believe it was a user error, you should do /createTeam <teamname> to make a team, I will add a proper error message for it

Staff is just a private chat thingy access list

**Comment by Thutmose** [comment]
it should specify now the usage for creating teams
