### ISSUE TITLE
How to use Blacklist?

### ISSUE THREAD

**Issue by Futschel** [Thutmose/ThutEssentials#31]
Hello, we have the Following proble with the Command Blacklist:

[19:26:07] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: An unknown error occurred while attempting to perform this command
[19:26:07] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: blacklist
java.lang.ArrayIndexOutOfBoundsException: 0
        at thut.essentials.commands.itemcontrol.Blacklist.func_184881_a(Blacklist.java:26) ~[Blacklist.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

How can we set Items on the Blacklist ?

**Comment by Thutmose** [comment]
you can either do it via the config file, or use `/blacklist add <item>` currently it works by item registry name, so if you wish players to not be able to use sticks, you need to use `/blacklist add minecraft:stick`
