### ISSUE TITLE
1.12.2-2.1.9 : Client-side ticking-entity crash on connect if landEnabled = true

### ISSUE THREAD

**Issue by UnixRonin** [Thutmose/ThutEssentials#34]
ThutPerms/ThutEssentials works fine as long as landEnabled = false.  If I set landEnabled = true, my dedicated server starts up with no problems, but my client crashes on connection with a ticking-entity error.  This behavior was first observed with thutpermissions-1.12.2-2.0.3.jar and thutessentials-1.12.2-2.1.6.jar, but is still present with thutpermissions-1.12.2-2.0.5.jar and thutessentials-1.12.2-2.1.9.jar.  The single factor governing whether the client crashes on connection of not is whether landEnabled is set true.  The specific ticking entity varies from one attempt to the next.

Relevant details of a representative crash log:

java.lang.NullPointerException: Ticking entity
at thut.essentials.land.LandEventsHandler.interactLeftClickEntity(LandEventsHandler.java:267)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_584_LandEventsHandler_interactLeftClickEntity_LivingAttackEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:571)
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848)
at net.minecraft.entity.passive.EntityBat.func_70097_a(SourceFile:203)
at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:232)
at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:269)
at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
at net.minecraft.entity.passive.EntityBat.func_70071_h_(SourceFile:112)
at net.minecraft.world.World.func_72866_a(World.java:1990)
at net.minecraft.world.World.func_72870_g(World.java:1952)
at net.minecraft.world.World.func_72939_s(World.java:1756)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at thut.essentials.land.LandEventsHandler.interactLeftClickEntity(LandEventsHandler.java:267)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_584_LandEventsHandler_interactLeftClickEntity_LivingAttackEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:571)
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:848)
at net.minecraft.entity.passive.EntityBat.func_70097_a(SourceFile:203)
at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:232)
at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:269)
at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
at net.minecraft.entity.passive.EntityBat.func_70071_h_(SourceFile:112)
at net.minecraft.world.World.func_72866_a(World.java:1990)
at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
Entity Type: minecraft:bat (net.minecraft.entity.passive.EntityBat)
Entity ID: 1668
Entity Name: Bat
Entity's Exact location: -501.02, 43.81, -1888.25
Entity's Block location: World: (-502,43,-1889), Chunk: (at 10,2,15 in -32,-119; contains blocks -512,0,-1904 to -497,255,-1889), Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537)
Entity's Momentum: 0.08, 0.00, 0.03
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1756)

**Comment by Thutmose** [comment]
the version with the fix for this has been uploaded to curseforge.

**Comment by UnixRonin** [comment]
Thank you!!!
