### ISSUE TITLE
Server Crash when expanding Backpack

### ISSUE THREAD

**Issue by Dranemra** [Thutmose/ThutEssentials#43]
#### Issue Description:
Recently installed ThutEssentials, have not fully explored tools, but when we try to expand a backpack from the Backpacks! mod, the server will crash. 

#### What happens:
Server crashes without warning. 
Following is the section of log that indicates its and issue with the Inventory Logger
Time: 10/6/18 11:11 AM
Description: Ticking player

java.lang.IndexOutOfBoundsException: Index: 87, Size: 86
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at thut.essentials.util.InventoryLogger$Listener.func_71111_a(InventoryLogger.java:40)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:91)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1731)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutessentials: 1.12.2-2.2-16
- Minecraft: 1.12.2
- Forge: 1.12.2-14223.4.2759-universal

**Comment by Thutmose** [comment]
Temporary workaround: set log_inventories to false in the config.

I will look into proper fixes when I have available time

**Comment by repairmant** [comment]
Also Ingeous Extruder & Glacial Precipitator both crash the whole server when switching types of output. using latest Thut Essentials ThermExp and stable forge

**Comment by Thutmose** [comment]
these should be fixed for next update.
